name: Print working directory

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print working directory
        run: echo "Working directory: $GITHUB_WORKSPACE"
